//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuan1-123
        ///
        ///Tuan2-123
        ///
        ///Tuan-123
        ///
        ///TuanPenspiner-123
        ///
        ///TuanPenspiner1-123
        ///
        ///TuanPenspine2-123
        ///
        ///TuanPenspine3-123
        ///
        ///TuanDepTrai-123
        ///
        ///.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hopstarter_Soft_Scraps_Button_Close {
            get {
                object obj = ResourceManager.GetObject("Hopstarter-Soft-Scraps-Button-Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons_Land_Vista_People_Office_Customer_Male_Light {
            get {
                object obj = ResourceManager.GetObject("Icons-Land-Vista-People-Office-Customer-Male-Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuan1-123.
        /// </summary>
        internal static string RememberPass {
            get {
                return ResourceManager.GetString("RememberPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gió âm thầm lướt qua muôn đời vì ai vì anh vì giờ anh biết chuyện tình mình chẳng còn gì,khi đó xuân sang người đừng ngọt lời thầm thì
        ///Em bước sang ngang đợi chờ điều gì diệu kì
        ///Như lúc ban đầu 
        ///Và giờ anh khóc thì cũng chẳng để làm gì
        ///Đâu phải cho anh,chuyện tình mình mà là vì
        ///Em đã trao ai dòng lệ tràn đầy cầu kì những năm tháng phai màu
        ///Nếu đóa hoa trồng trước kia chưa về,nhánh hương tình thắm thêm câu thề
        ///Anh ước rằng,rằng một mai anh đến anh đón em vào sớm mai trong lành
        ///Nhưng đó mãi là giấc mơ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Usename {
            get {
                object obj = ResourceManager.GetObject("Usename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
